services:
  flask_api:
    build: ./python-api
    container_name: python-api
    ports: 
      - "5000:5000"
    command: "python app.py"
    depends_on:
      - mysql_db
    networks:
      - app-network

  express_api:
    build: ./nodejs-api
    container_name: node-api
    ports: 
      - "3000:3000"
    command: "node index.js"
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: "mysql:5.6"
    environment:
      MYSQL_USER: aula
      MYSQL_PASSWORD: aula6
      MYSQL_ROOT_PASSWORD: aula6
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: