services:
  flask_api:
    build: ./python-api
    container_name: python-api
    ports: 
      - "5000:5000"
    volumes: 
      - ./python-api:/app
    command: "python app.py"
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: "mysql:5.6"
    environment:
      MYSQL_USER: aula
      MYSQL_PASSWORD: aula6
      MYSQL_ROOT_PASSWORD: aula6
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: